import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
import { DashboardView } from "../src/features/dashboard/DashboardView";
import { DesignLibraryView } from "../src/features/design-library/DesignLibraryView";
import { FilamentView } from "../src/features/filament/FilamentView";
import { PlanningView } from "../src/features/planning/PlanningView";
import { PrintersView } from "../src/features/printers/PrintersView";
import { ProductionView } from "../src/features/production/ProductionView";
import { ReportsView } from "../src/features/reports/ReportsView";
import { SettingsView } from "../src/features/settings/SettingsView";
import { WorkspaceSetupView } from "../src/features/setup/WorkspaceSetupView";
import { fallbackSettings } from "../src/lib/cost";
import type { ForgekeeperState } from "../src/state/useForgekeeperState";

function emptyState(): ForgekeeperState {
  const noop = vi.fn();
  const state = {
    view: "dashboard",
    isReady: true,
    storageBackend: "browser-preview",
    storageError: "",
    legacyImported: false,
    settings: { ...fallbackSettings, setupCompleted: true },
    designProjects: [],
    stls: [],
    concepts: [],
    variants: [],
    collections: [],
    releases: [],
    productionJobs: [],
    productionBatches: [],
    filament: [],
    materialMovements: [],
    printers: [],
    maintenance: [],
    costSnapshots: [],
    activityLog: [],
    intakePackets: [],
    prototypes: [],
    plannedFilament: [],
    designPlanning: [],
    realmMaterials: [],
    filteredDesignProjects: [],
    selectedDesignProjectId: "",
    selectedDesignProject: undefined,
    designStls: [],
    designConcepts: [],
    designJobs: [],
    designVariants: [],
    designRelease: undefined,
    designTab: "overview",
    quickAction: null,
    newDesignName: "",
    newStlName: "",
    newConceptTitle: "",
    newCollectionName: "",
    newReleaseName: "",
    newJobName: "",
    newBatchName: "",
    newFilamentName: "",
    newPrinterName: "",
    newPrototypeName: "",
    newPlannedFilamentName: "",
    newDesignPlanningName: "",
    searchTerm: "",
    queueCounts: { Queued: 0, Printing: 0, Finishing: 0, Complete: 0, Cancelled: 0 },
    metrics: {
      designProjects: 0,
      stls: 0,
      concepts: 0,
      variants: 0,
      collections: 0,
      releases: 0,
      productionJobs: 0,
      filament: 0,
      printers: 0,
      costs: 0,
      printing: 0,
      done: 0,
      totalFilamentKg: 0,
    },
    productionMetrics: {
      totalQueueHours: 0,
      assignedQueueHours: 0,
      unassignedQueueHours: 0,
      estimatedCompletionHours: 0,
      estimatedCompletionDays: 0,
      filamentNeededGrams: 0,
      printerLoads: [],
      filamentDemand: [],
      bottlenecks: [],
      unassignedJobs: 0,
    },
    integrityIssues: [],
    getCostBreakdownForJob: vi.fn(),
    getDesignCostGuide: vi.fn(),
    getPrimaryStlForDesign: vi.fn(),
    getLatestConceptForDesign: vi.fn(),
    getDesignDisplayImage: vi.fn(() => ""),
    getVariantDisplayImage: vi.fn(() => ""),
    setView: noop,
    setSelectedDesignProjectId: noop,
    setDesignTab: noop,
    setNewDesignName: noop,
    setNewStlName: noop,
    setNewConceptTitle: noop,
    setNewCollectionName: noop,
    setNewReleaseName: noop,
    setNewJobName: noop,
    setNewBatchName: noop,
    setNewFilamentName: noop,
    setNewPrinterName: noop,
    setNewPrototypeName: noop,
    setNewPlannedFilamentName: noop,
    setNewDesignPlanningName: noop,
    setSearchTerm: noop,
    setPrototypes: noop,
    setPlannedFilament: noop,
    setDesignPlanning: noop,
    setRealmMaterials: noop,
    triggerQuickAction: noop,
    addDesign: noop,
    updateDesign: noop,
    removeDesign: noop,
    addStl: noop,
    updateStl: noop,
    markPrimaryStl: noop,
    removeStl: noop,
    addConcept: noop,
    updateConcept: noop,
    removeConcept: noop,
    addVariant: noop,
    updateVariant: noop,
    removeVariant: noop,
    addCollection: noop,
    updateCollection: noop,
    removeCollection: noop,
    assignDesignToCollection: noop,
    setCollectionHero: noop,
    addRelease: noop,
    updateRelease: noop,
    removeRelease: noop,
    addDesignToRelease: noop,
    removeDesignFromRelease: noop,
    addProductionJob: noop,
    updateProductionJob: noop,
    removeProductionJob: noop,
    consumeFilamentForJob: noop,
    addProductionBatch: noop,
    updateProductionBatch: noop,
    removeProductionBatch: noop,
    addFilament: noop,
    updateFilament: noop,
    adjustFilament: noop,
    removeFilament: noop,
    addPrinter: noop,
    updatePrinter: noop,
    restoreWorkshopPrinterProfiles: noop,
    removePrinter: noop,
    addMaintenance: noop,
    updateMaintenance: noop,
    removeMaintenance: noop,
    updateSettings: noop,
    importForgepack: noop,
    completeSetup: noop,
    addPrototype: noop,
    updatePrototype: noop,
    removePrototype: noop,
    promotePrototypeToDesign: noop,
    addPlannedFilament: noop,
    updatePlannedFilament: noop,
    removePlannedFilament: noop,
    movePlannedFilamentToInventory: noop,
    addDesignPlanning: noop,
    updateDesignPlanning: noop,
    removeDesignPlanning: noop,
    getDefaultSlicerForPrinter: vi.fn(() => "orca"),
    getPreferredSlicerForStl: vi.fn(() => "orca"),
    suggestStlLibraryFolder: vi.fn(() => ""),
    suggestConceptLibraryFolder: vi.fn(() => ""),
    linkStlPath: noop,
    setStlSuggestedFolder: noop,
    openStlAsset: noop,
    openManagedAsset: noop,
    openExternalTool: noop,
    exportDesignProjectsCsv: noop,
    exportStlsCsv: noop,
    exportConceptsCsv: noop,
    exportVariantsCsv: noop,
    exportCollectionsCsv: noop,
    exportReleasesCsv: noop,
    exportProductionJobsCsv: noop,
    exportFilamentCsv: noop,
    exportMaterialMovementsCsv: noop,
    exportPrintersCsv: noop,
    exportMaintenanceCsv: noop,
    exportProductionBatchesCsv: noop,
    exportCostSnapshotsCsv: noop,
    exportActivityLogCsv: noop,
    exportBackupJson: noop,
    importBackupFile: noop,
    resetWorkspace: noop,
  };
  return state as unknown as ForgekeeperState;
}

describe("station UI smoke test", () => {
  it("renders every active station and first-run setup with an empty workspace", () => {
    const state = emptyState();
    const views = [
      <DashboardView state={state} />,
      <DesignLibraryView state={state} />,
      <PlanningView state={state} />,
      <ProductionView state={state} />,
      <FilamentView state={state} />,
      <PrintersView state={state} />,
      <ReportsView state={state} />,
      <SettingsView state={state} />,
      <WorkspaceSetupView state={{ ...state, settings: { ...state.settings, setupCompleted: false } }} />,
    ];

    for (const view of views) {
      expect(renderToStaticMarkup(view).length).toBeGreaterThan(100);
    }
  });
});
