import type { WorkerCapability } from "./types";

export const MeshCapabilities = {
  meshReadState: "mesh.read-state",
  meshPublishEvent: "mesh.publish-event",
  meshRequestResource: "mesh.request-resource",
  meshManageWorker: "mesh.manage-worker",
  meshEnterSafeMode: "mesh.enter-safe-mode",
  meshExitSafeMode: "mesh.exit-safe-mode",
  productionRead: "production.read",
  productionWrite: "production.write",
  productionCheckpointCreate: "production.checkpoint.create",
  productionThoughtCapture: "production.thought.capture",
  productionRecommendNextAction: "production.next-action.recommend",
  productionAdvanceStage: "production.stage.advance",
  watcherReadTelemetry: "watcher.telemetry.read",
  watcherPublishFinding: "watcher.finding.publish",
  watcherSuspendHeavyCompute: "watcher.compute.suspend-heavy",
  foundryCanonRead: "foundry.canon.read",
  foundryCanonWrite: "foundry.canon.write",
  foundryProjectRead: "foundry.project.read",
  foundryProjectWrite: "foundry.project.write",
  foundrySessionRead: "foundry.session.read",
  foundrySessionWrite: "foundry.session.write",
  foundryDecisionRead: "foundry.decision.read",
  foundryDecisionWrite: "foundry.decision.write",
  systemServiceStart: "system.service.start",
  systemServiceStop: "system.service.stop",
  systemServiceRestart: "system.service.restart",
  workstationLaunchTool: "workstation.tool.launch",
  workstationOpenPath: "workstation.path.open",
} as const;

export type MeshCapabilityId = (typeof MeshCapabilities)[keyof typeof MeshCapabilities];

export const defaultCapabilityCatalog: WorkerCapability[] = [
  { id: MeshCapabilities.meshReadState, name: "Read Mesh State", risk: "read" },
  { id: MeshCapabilities.meshPublishEvent, name: "Publish Mesh Event", risk: "low" },
  { id: MeshCapabilities.meshRequestResource, name: "Request Managed Resource", risk: "low" },
  { id: MeshCapabilities.meshManageWorker, name: "Manage Worker", risk: "high" },
  { id: MeshCapabilities.meshEnterSafeMode, name: "Enter Safe Mode", risk: "critical" },
  { id: MeshCapabilities.meshExitSafeMode, name: "Exit Safe Mode", risk: "critical" },
  { id: MeshCapabilities.productionRead, name: "Read Production State", risk: "read" },
  { id: MeshCapabilities.productionWrite, name: "Modify Production State", risk: "moderate" },
  { id: MeshCapabilities.productionCheckpointCreate, name: "Create Production Checkpoint", risk: "low" },
  { id: MeshCapabilities.productionThoughtCapture, name: "Capture Production Thought", risk: "low" },
  { id: MeshCapabilities.productionRecommendNextAction, name: "Recommend Next Production Action", risk: "low" },
  { id: MeshCapabilities.productionAdvanceStage, name: "Advance Production Stage", risk: "moderate" },
  { id: MeshCapabilities.watcherReadTelemetry, name: "Read Watcher Telemetry", risk: "read" },
  { id: MeshCapabilities.watcherPublishFinding, name: "Publish Watcher Finding", risk: "low" },
  { id: MeshCapabilities.watcherSuspendHeavyCompute, name: "Suspend Heavy Compute", risk: "high" },
  { id: MeshCapabilities.foundryCanonRead, name: "Read Foundry Canon", risk: "read" },
  { id: MeshCapabilities.foundryCanonWrite, name: "Modify Foundry Canon", risk: "critical" },
  { id: MeshCapabilities.foundryProjectRead, name: "Read Foundry Project State", risk: "read" },
  { id: MeshCapabilities.foundryProjectWrite, name: "Modify Foundry Project State", risk: "moderate" },
  { id: MeshCapabilities.foundrySessionRead, name: "Read Foundry Session State", risk: "read" },
  { id: MeshCapabilities.foundrySessionWrite, name: "Modify Foundry Session State", risk: "moderate" },
  { id: MeshCapabilities.foundryDecisionRead, name: "Read Foundry Decisions", risk: "read" },
  { id: MeshCapabilities.foundryDecisionWrite, name: "Record Foundry Decisions", risk: "moderate" },
  { id: MeshCapabilities.systemServiceStart, name: "Start Managed Service", risk: "moderate" },
  { id: MeshCapabilities.systemServiceStop, name: "Stop Managed Service", risk: "high" },
  { id: MeshCapabilities.systemServiceRestart, name: "Restart Managed Service", risk: "high" },
  { id: MeshCapabilities.workstationLaunchTool, name: "Launch Workstation Tool", risk: "moderate" },
  { id: MeshCapabilities.workstationOpenPath, name: "Open Workstation Path", risk: "low" },
];
