export const MeshEvents = {
  meshInitialized: "mesh.initialized",
  meshSnapshotSaved: "mesh.snapshot.saved",
  systemSafeModeEntered: "system.safe-mode.entered",
  systemSafeModeExited: "system.safe-mode.exited",
  workerRegistered: "worker.registered",
  workerStarted: "worker.started",
  workerStopped: "worker.stopped",
  workerFailed: "worker.failed",
  workerRecovered: "worker.recovered",
  workerHeartbeat: "worker.heartbeat",
  workerCommissioningStateChanged: "worker.commissioning.state-changed",
  serviceRegistered: "service.registered",
  serviceStateChanged: "service.state.changed",
  domainRecordChanged: "domain.record.changed",
  resourceStateChanged: "resource.state.changed",
  resourceLeaseGranted: "resource.lease.granted",
  resourceLeaseDenied: "resource.lease.denied",
  resourceLeaseReleased: "resource.lease.released",
  productionSessionStarted: "production.session.started",
  productionSessionEnded: "production.session.ended",
  productionActionCompleted: "production.action.completed",
  productionBlockerDetected: "production.blocker.detected",
  productionCheckpointCreated: "production.checkpoint.created",
  productionThoughtCaptured: "production.thought.captured",
  watcherFindingPublished: "watcher.finding.published",
  watcherAnomalyDetected: "watcher.anomaly.detected",
  watcherDegradationDetected: "watcher.degradation.detected",
  ollamaModelLoaded: "ollama.model.loaded",
  ollamaModelUnloaded: "ollama.model.unloaded",
  actionApprovalRequested: "action.approval.requested",
  actionApproved: "action.approved",
  actionDenied: "action.denied",
  actionCompleted: "action.completed",
  actionFailed: "action.failed",
} as const;

export type MeshEventName = (typeof MeshEvents)[keyof typeof MeshEvents];
