import { MeshCapabilities } from "./catalog";
import type { WorkerIdentity } from "./types";

export const FoundryWorkers: Record<string, WorkerIdentity> = {
  foundryCore: {
    id: "foundry-core",
    name: "Foundry Core",
    kind: "foundry-core",
    description: "Authoritative operational state and governance services for the Foundry ecosystem.",
    capabilities: [
      MeshCapabilities.meshReadState,
      MeshCapabilities.meshPublishEvent,
      MeshCapabilities.foundryProjectRead,
      MeshCapabilities.foundryProjectWrite,
      MeshCapabilities.foundryCanonRead,
      MeshCapabilities.foundryCanonWrite,
      MeshCapabilities.foundrySessionRead,
      MeshCapabilities.foundrySessionWrite,
      MeshCapabilities.foundryDecisionRead,
      MeshCapabilities.foundryDecisionWrite,
      MeshCapabilities.productionRead,
      MeshCapabilities.productionWrite,
      MeshCapabilities.productionThoughtCapture,
    ],
    enabled: true,
    commissioningState: "active",
  },
  forgekeeper: {
    id: "forgekeeper",
    name: "Forgekeeper",
    kind: "forgekeeper",
    description: "Foundry coordination and operational stewardship worker.",
    capabilities: [
      MeshCapabilities.meshReadState,
      MeshCapabilities.meshPublishEvent,
      MeshCapabilities.foundryProjectRead,
      MeshCapabilities.productionRead,
      MeshCapabilities.foundrySessionRead,
      MeshCapabilities.foundryDecisionRead,
    ],
    enabled: false,
    commissioningState: "dormant",
  },
  forgekeeperMobile: {
    id: "forgekeeper-mobile",
    name: "Forgekeeper Mobile Console",
    kind: "forgekeeper",
    description: "Human-operated roaming Foundry console. Requests arrive only through an authenticated Foundry Link pairing and remain subject to Mesh permissions and approvals.",
    capabilities: [
      MeshCapabilities.meshReadState,
      MeshCapabilities.meshPublishEvent,
      MeshCapabilities.productionRead,
      MeshCapabilities.foundryProjectRead,
      MeshCapabilities.foundrySessionRead,
      MeshCapabilities.foundryDecisionRead,
      MeshCapabilities.watcherReadTelemetry,
      MeshCapabilities.systemServiceStart,
      MeshCapabilities.systemServiceStop,
      MeshCapabilities.systemServiceRestart,
      MeshCapabilities.workstationLaunchTool,
      MeshCapabilities.workstationOpenPath,
    ],
    enabled: true,
    commissioningState: "active",
  },
  productionSteward: {
    id: "production-steward",
    name: "Production Steward",
    kind: "production-steward",
    description: "Executive-function support, production continuity, re-entry, blocker handling, and captured-thought routing.",
    capabilities: [
      MeshCapabilities.meshReadState,
      MeshCapabilities.meshPublishEvent,
      MeshCapabilities.meshRequestResource,
      MeshCapabilities.productionRead,
      MeshCapabilities.productionWrite,
      MeshCapabilities.productionCheckpointCreate,
      MeshCapabilities.productionThoughtCapture,
      MeshCapabilities.productionRecommendNextAction,
      MeshCapabilities.productionAdvanceStage,
      MeshCapabilities.foundrySessionRead,
      MeshCapabilities.foundrySessionWrite,
      MeshCapabilities.foundryDecisionRead,
    ],
    enabled: false,
    commissioningState: "dormant",
  },
  watcher: {
    id: "watcher",
    name: "The Watcher",
    kind: "watcher",
    description: "Machine health, anomaly, degradation, and recovery-awareness worker.",
    capabilities: [
      MeshCapabilities.meshReadState,
      MeshCapabilities.meshPublishEvent,
      MeshCapabilities.watcherReadTelemetry,
      MeshCapabilities.watcherPublishFinding,
      MeshCapabilities.watcherSuspendHeavyCompute,
    ],
    enabled: false,
    commissioningState: "dormant",
  },
  bastion: {
    id: "bastion",
    name: "Bastion",
    kind: "bastion",
    description: "Physical supervisory and command surface for the local Foundry mesh.",
    capabilities: [
      MeshCapabilities.meshReadState,
      MeshCapabilities.meshPublishEvent,
      MeshCapabilities.meshManageWorker,
      MeshCapabilities.meshEnterSafeMode,
      MeshCapabilities.meshExitSafeMode,
      MeshCapabilities.watcherReadTelemetry,
      MeshCapabilities.systemServiceStart,
      MeshCapabilities.systemServiceStop,
      MeshCapabilities.systemServiceRestart,
      MeshCapabilities.foundrySessionRead,
    ],
    enabled: false,
    commissioningState: "dormant",
  },
  openclaw: {
    id: "openclaw",
    name: "OpenClaw",
    kind: "openclaw",
    description: "Automation, scheduling, hooks, and authorized background execution worker.",
    capabilities: [
      MeshCapabilities.meshReadState,
      MeshCapabilities.meshPublishEvent,
      MeshCapabilities.meshRequestResource,
      MeshCapabilities.foundryProjectRead,
      MeshCapabilities.productionRead,
      MeshCapabilities.foundrySessionRead,
      MeshCapabilities.systemServiceStart,
      MeshCapabilities.systemServiceRestart,
    ],
    enabled: false,
    commissioningState: "dormant",
  },
  odysseus: {
    id: "odysseus",
    name: "Odysseus",
    kind: "odysseus",
    description: "Local conversational, research, and personal cognitive workspace.",
    capabilities: [
      MeshCapabilities.meshReadState,
      MeshCapabilities.meshPublishEvent,
      MeshCapabilities.meshRequestResource,
      MeshCapabilities.foundryProjectRead,
      MeshCapabilities.foundryCanonRead,
      MeshCapabilities.productionRead,
      MeshCapabilities.productionThoughtCapture,
      MeshCapabilities.foundrySessionRead,
      MeshCapabilities.foundrySessionWrite,
      MeshCapabilities.foundryDecisionRead,
    ],
    enabled: false,
    commissioningState: "dormant",
  },
  ollama: {
    id: "ollama",
    name: "Ollama",
    kind: "ollama",
    description: "Shared local inference provider for mesh workers.",
    capabilities: [MeshCapabilities.meshReadState, MeshCapabilities.meshPublishEvent, MeshCapabilities.meshRequestResource],
    enabled: false,
    commissioningState: "dormant",
  },
};

export const defaultFoundryWorkers = Object.values(FoundryWorkers);
